### ISSUE TITLE
[Feature Request] `getTsAtIntersection`

### ISSUE THREAD

**Issue by RebeccaStevens** [FlorisSteenkamp/FloBezier#22]
Like the `bezierBezierIntersectionFast`, but it returns the t values at which the points intersect.

**Comment by FlorisSteenkamp** [comment]
`bezierBezierIntersectionFast` actually only returns the `t` value pairs, e.g. for a return value of `ts === [[0.1,0.2]]` the first `0.1` is the t value for the first bezier and the `0.2` is for the second bezier. Each entry of the return value represents an individual intersection.

To get the actual points of intersection you have to do a little more work (I repost the code here): 

```typescript
import { bezierBezierIntersectionFast, evalDeCasteljau } from "flo-bezier3";

const bezCubic     = [[0,0],[1,1],[2,1],[3,7]];
const bezQuadratic = [[2,0],[1,1],[3,7]];
const bezLine      = [[-1,-1],[5,5]];


// Intersection of cubic bezier and a line
const tPairs1 = bezierBezierIntersectionFast(bezCubic,bezLine);
// tPairs1 === [[-1.1102230246251496e-16, 0.16666666666666657], [0.4285714285714285, 0.380952380952381]]
const points1 = tPairs1.map(tPair => evalDeCasteljau(bezCubic, tPair[0]));
// points1 === [[-3.330669073875449e-16, -3.330669073875449e-16], [1.2857142857142854, 1.2857142857142856]]

// Intersection of quadratic bezier and a line
const tPairs2 = bezierBezierIntersectionFast(bezQuadratic,bezLine);
// tPairs2 === [[ 0.41421356237309515, 0.4477152501692065]]
const points2 = tPairs2.map(tPair => evalDeCasteljau(bezQuadratic, tPair[0]));
// points2 === [[1.6862915010152397, 1.6862915010152402]]
```

As a side note, you can use `bezierBezierIntersection` instead to get the `t` values and points at the same time with additional information such as the guaranteed `t` interval containing an intersection.

`bezierBezierIntersectionFast` calculates > 50 intersections per millisecond (if I remember correctly), and has a guaranteed accuracy of 2^-33 whereas `bezierBezierIntersection` calculates about 10 per millisecond (again, if I remember correctly) and has a guaranteed accuracy of 2^-51. Both algorithms have a guaranteed fast runtime. This is NOT possible using any bezier clipping algorithm on its own.
