### ISSUE TITLE
[Feature Request] `getTsAtX`/`getTsAtY`

### ISSUE THREAD

**Issue by RebeccaStevens** [FlorisSteenkamp/FloBezier#23]
The ability to get the t values at which the x/y value is off a given value.

**Comment by FlorisSteenkamp** [comment]
If I understand you correctly you want to calculate the `t` values where a bezier curve attains at a certain x or y value. For lines (order 1 linear bezier curves) there can be at most 1 such point, for quadratic bezier curves (which are exactly just parts of translated, scaled and rotated versions of the explicit unit quadratic curve) there can be at most two. For cubic bezier curves there can be at most 3, etc.

It seems there is not such a built-in function in the library yet. Thanks, I'll add them and comment back here. In the meantime, a simple solution is to intersect a (boundless) vertical or horizontal line with the bezier curve. Code follows:

```typescript
const bezCubic = [[0,0],[1,1],[2,1],[3,7]];  // Some cubic bezier curve

const x = 0.8;  // Some `x` value for which you want to find the `t` values and/or `y` values
const y = 1.7;  // Some `y` value for which you want to find the `t` values and/or `x` values
const verticalLine = [[x,0],[x,1]]
const horizontalLine = [[0,y],[1,y]]

//--------------------------------------------------------
// Find `t` values and `y` values for a specific `x` value
//--------------------------------------------------------
const tsAtX = bezierBezierIntersectionBoundless(verticalLine, bezCubic)!
    .map(r => (r.tS + r.tE)/2);  // take the center of the root interval (guaranteed within 4 ulps accurate)
// tsAtX === [0.2666666666666668]
const pointsAtX =  tsAtX.map(t => evalDeCasteljau(bezCubic,t));
// points === [[ 0.8000000000000003, 0.7194074074074077 ]];
const yValuesAtX = pointsAtX.map(p => p[1]);
// yValuesAtX === [0.7194074074074077]


//--------------------------------------------------------
// Find `t` values and `x` values for a specific `y` value
//--------------------------------------------------------
const tsAtY = bezierBezierIntersectionBoundless(horizontalLine, bezCubic)!
    .map(r => (r.tS + r.tE)/2);  // take the center of the root interval (guaranteed within 4 ulps accurate)
// tsAtY === [0.5140019750623149]
const pointsAtY =  tsAtY.map(t => evalDeCasteljau(bezCubic,t));
// points === [[1.5420059251869445, 1.6999999999999997]]
const xValuesAtY = pointsAtY.map(p => p[1]);
// xValuesAtY === [ 1.6999999999999997 ]
```

**Comment by RebeccaStevens** [comment]
That does what I want, thanks.

Is there any order to the returned t values? For example, if I just wanted the smallest t value, would it always be first in the array, or is the array order non-deterministic?

**Comment by FlorisSteenkamp** [comment]
Yes, the `t` values are always ordered from smallest to largest.

Just keep in mind that there could obviously be no `y` value for some `x` value (and vice versa) thus returning an empty array. This is so since bezier curves are limited in length by their parameter values being limited to the range `[0,1]`
